apiVersion: v1
kind: Service
metadata:
  labels:
    name: bind9-service 
    visualize: "true"
  name: bind9-service
spec:
  externalIPs:
  - 67.58.50.101
  ports:
    - port: 53 
      targetPort: 53
      protocol: UDP
  selector:
    app: bind9-service

