apiVersion: v1
kind: Service
metadata:
  labels:
    name: bind9-service 
    visualize: "true"
  name: bind9-service
spec:
  ports:
    - port: 53 
      protocol: UDP
  selector:
    app: bind9-service
